//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControlRutas.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ControlRutasEntities : DbContext
    {
        public ControlRutasEntities()
            : base("name=ControlRutasEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AspNetRoles> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaims> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogins> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUsers> AspNetUsers { get; set; }
        public virtual DbSet<Eventos> Eventos { get; set; }
        public virtual DbSet<MediosTransporte> MediosTransporte { get; set; }
        public virtual DbSet<TiposEventos> TiposEventos { get; set; }
        public virtual DbSet<TiposMediosTransporte> TiposMediosTransporte { get; set; }
        public virtual DbSet<TiposUsuarios> TiposUsuarios { get; set; }
        public virtual DbSet<UsuariosEstudiantes> UsuariosEstudiantes { get; set; }
        public virtual DbSet<UsuariosMediosTransporte> UsuariosMediosTransporte { get; set; }
        public virtual DbSet<UsuariosEstablecimientos> UsuariosEstablecimientos { get; set; }
        public virtual DbSet<Usuarios> Usuarios { get; set; }
        public virtual DbSet<RutasMediosTransporte> RutasMediosTransporte { get; set; }
        public virtual DbSet<NoUsoRutasMediosTransporte> NoUsoRutasMediosTransporte { get; set; }
        public virtual DbSet<Perfiles> Perfiles { get; set; }
        public virtual DbSet<PerfilesPermisos> PerfilesPermisos { get; set; }
        public virtual DbSet<Permisos> Permisos { get; set; }
        public virtual DbSet<UsuariosPermisos> UsuariosPermisos { get; set; }
        public virtual DbSet<EstudiantesMediosTransporte> EstudiantesMediosTransporte { get; set; }
        public virtual DbSet<Estudiantes> Estudiantes { get; set; }
        public virtual DbSet<EstablecimientosEducativos> EstablecimientosEducativos { get; set; }
    }
}
