//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControlRutas.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class EstudiantesMediosTransporte
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EstudiantesMediosTransporte()
        {
            this.NoUsoRutasMediosTransporte = new HashSet<NoUsoRutasMediosTransporte>();
            this.RutasMediosTransporte = new HashSet<RutasMediosTransporte>();
        }
    
        public int Id { get; set; }
        public string GUID { get; set; }
        public int IdCodigoEstudiante { get; set; }
        public int IdCodigoMedioTransporte { get; set; }
        public string DireccionOrigen { get; set; }
        public string LatitudOrigen { get; set; }
        public string LongitudOrigen { get; set; }
        public string DireccionDestino { get; set; }
        public string LatitudDestino { get; set; }
        public string LongitudDestino { get; set; }
    
        public virtual Estudiantes Estudiantes { get; set; }
        public virtual MediosTransporte MediosTransporte { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NoUsoRutasMediosTransporte> NoUsoRutasMediosTransporte { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RutasMediosTransporte> RutasMediosTransporte { get; set; }
    }
}
