//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControlRutas.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class MediosTransporte
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MediosTransporte()
        {
            this.UsuariosMediosTransporte = new HashSet<UsuariosMediosTransporte>();
            this.EstudiantesMediosTransporte = new HashSet<EstudiantesMediosTransporte>();
        }
    
        public int Id { get; set; }
        public string GUID { get; set; }
        public int IdCodigoPiloto { get; set; }
        public int IdCodigoDueño { get; set; }
        public int IdCodigoEstablecimiento { get; set; }
        public int IdTipoMedioTransporte { get; set; }
        public string Identificador { get; set; }
        public string Placa { get; set; }
        public string Color { get; set; }
        public bool Estado { get; set; }
    
        public virtual TiposMediosTransporte TiposMediosTransporte { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UsuariosMediosTransporte> UsuariosMediosTransporte { get; set; }
        public virtual Usuarios Usuarios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EstudiantesMediosTransporte> EstudiantesMediosTransporte { get; set; }
        public virtual EstablecimientosEducativos EstablecimientosEducativos { get; set; }
    }
}
