//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControlRutas.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class RutasMediosTransporte
    {
        public int Id { get; set; }
        public string GUID { get; set; }
        public int IdEstudianteMedioTransporte { get; set; }
        public System.DateTime Fecha { get; set; }
        public string Grado { get; set; }
        public string DireccionOrigen { get; set; }
        public string LatitudOrigen { get; set; }
        public string LongitudOrigen { get; set; }
        public string DireccionDestino { get; set; }
        public string LatitudDestino { get; set; }
        public string LongitudDestino { get; set; }
        public int Orden { get; set; }
        public System.DateTime HoraSalida { get; set; }
        public System.DateTime HoraLlegada { get; set; }
    
        public virtual EstudiantesMediosTransporte EstudiantesMediosTransporte { get; set; }
    }
}
