//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControlRutas.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuarios
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Usuarios()
        {
            this.MediosTransporte = new HashSet<MediosTransporte>();
            this.UsuariosEstudiantes = new HashSet<UsuariosEstudiantes>();
            this.UsuariosMediosTransporte = new HashSet<UsuariosMediosTransporte>();
        }
    
        public int Id { get; set; }
        public string GUID { get; set; }
        public string PrimerNombre { get; set; }
        public string SegundoNombre { get; set; }
        public string PrimerApellido { get; set; }
        public string SegundoApellido { get; set; }
        public string Email { get; set; }
        public string NumeroTelefono { get; set; }
        public int IdTipoUsuario { get; set; }
        public int Estado { get; set; }
        public int IdEstablecimiento { get; set; }
    
        public virtual EstablecimientosEducativos EstablecimientosEducativos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MediosTransporte> MediosTransporte { get; set; }
        public virtual TiposUsuarios TiposUsuarios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UsuariosEstudiantes> UsuariosEstudiantes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UsuariosMediosTransporte> UsuariosMediosTransporte { get; set; }
    }
}
